version: "3.9"
services:
  loadbalancer:
    image: traefik:2.9.9
    command: --providers.docker --entrypoints.web.address=:80 --api.insecure=true
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  app-a:
    image: "codyja@akin-app:v1.0.0"
    ports:
      - "8001:8001"
    environment:
      - "BIND_PORT=8001"
      - "CONTAINER_NAME=service-A"
      - "BG_COLOR=Tomato"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myapp.rule=HostRegexp(`{subdomain:.+}.ngrok.io`) || Host(`localhost`)"
      - "traefik.http.services.myapp.loadbalancer.server.port=8001"
  app-B:
    image: "codyja@akin-app:v1.0.0"
    ports:
      - "8002:8002"
    environment:
      - "BIND_PORT=8002"
      - "CONTAINER_NAME=service-B"
      - "BG_COLOR=DodgerBlue"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myapp.rule=HostRegexp(`{subdomain:.+}.ngrok.io`) || Host(`localhost`)"
      - "traefik.http.services.myapp.loadbalancer.server.port=8002"